import { SupportedChainId } from "@/types/network/supportedNetworks";
import { MAINNET_CONTRACTS, SEPOLIA_CONTRACTS, THANOS_SEPOLIA_CONTRACTS, TITAN_SEPOLIA_CONTRACTS, TOKAMAK_CONTRACTS } from "./contracts";

export const TON_ADDRESS_BY_CHAINID: Record<number, string> = {
  // [SupportedChainId.MAINNET]: MAINNET_CONTRACTS.TON_ADDRESS,
  // [SupportedChainId.TITAN]: TOKAMAK_CONTRACTS.TON_ADDRESS,
  [SupportedChainId.TITAN_SEPOLIA]: TITAN_SEPOLIA_CONTRACTS.TON_ADDRESS,
  [SupportedChainId.SEPOLIA]: SEPOLIA_CONTRACTS.L1_TON,
  [SupportedChainId.THANOS_SEPOLIA]: THANOS_SEPOLIA_CONTRACTS.TON_ADDRESS
};

export const WSWTON_ADDRESS_BY_CHAINID:Record<number, string> = {
  // [SupportedChainId.MAINNET]: "",
  [SupportedChainId.TITAN_SEPOLIA]: TITAN_SEPOLIA_CONTRACTS.WSTON_ADDRESS,
  [SupportedChainId.SEPOLIA]: SEPOLIA_CONTRACTS.L1_WRAPPED_STAKED_TON_PROXY,
  [SupportedChainId.THANOS_SEPOLIA]: THANOS_SEPOLIA_CONTRACTS.TITAN_WRAPPED_STAKED_TON
}

export const FACTORY_ADDRESS:Record<number, string> = {
  [SupportedChainId.TITAN_SEPOLIA] : TITAN_SEPOLIA_CONTRACTS.GEMFACTORY,
  [SupportedChainId.THANOS_SEPOLIA] : THANOS_SEPOLIA_CONTRACTS.GEM_FACTORY_PROXY
}

export const MARKETPLACE_ADDRESS:Record<number, string> = {
  [SupportedChainId.TITAN_SEPOLIA] : TITAN_SEPOLIA_CONTRACTS.MARKETPLACE,
  [SupportedChainId.THANOS_SEPOLIA] : THANOS_SEPOLIA_CONTRACTS.MARKETPLACE_PROXY
}

export const GEMPACK_ADDRESS:Record<number, string> = {
  [SupportedChainId.TITAN_SEPOLIA] : TITAN_SEPOLIA_CONTRACTS.GEMPACK,
  [SupportedChainId.THANOS_SEPOLIA] : THANOS_SEPOLIA_CONTRACTS.RANDOM_PACK_PROXY
}

export const DRB_ADDRESS:Record<number, string> = {
  [SupportedChainId.TITAN_SEPOLIA] : TITAN_SEPOLIA_CONTRACTS.DRB_COORDINATOR,
  [SupportedChainId.THANOS_SEPOLIA] : THANOS_SEPOLIA_CONTRACTS.DRB_COORDINATOR_MOCK
}